env:
  browser: true
  es2021: true
extends: eslint:recommended
globals:
  AbsoluteOrientationSensor:
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
